// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtapittbvjcjzoivsofx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0YXBpdHRidmpjanpvaXZzb2Z4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgyMTY5MDAsImV4cCI6MjA4Mzc5MjkwMH0.PEdftkCBQUWhXiwFAwMFPDHJ3ceUbQGlAmWEf5sV1Wo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
